### ISSUE TITLE
CAD End Effector

### ISSUE THREAD

**Issue by HarrisonMKG** [HarrisonMKG/pen-pal#15]
Create a CAD model for the end effector and print

- [x] Complete CAD
- [x] Print
- [x] Test/Verify

**Comment by Krsikapa00** [comment]
2 models have been created. Both follow the same design however one uses a larger radius to hold the pen, this is so the rest of the end effector is less likely to interfere with the writing surface.

The current prototypes fit on the model well however have not been tested to write anything yet
